FROM node:12

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production


# Bundle app source
COPY . .

# Build React App 
RUN cd client && npm install && npm run build

EXPOSE 8080
CMD [ "node", "server.js" ]